FROM cpswarm/gazebo-simulator:latest

RUN echo "source /opt/ros/kinetic/setup.bash" >> ~/.bashrc \
		  && /bin/bash -c "source ~/.bashrc"

RUN git clone https://github.com/cpswarm/GazeboSimulationManager.git

COPY . $HOME

WORKDIR $HOME/it.ismb.pert.cpswarm.simulation.gazebo

RUN bnd package gazeboManager.bndrun

COPY gazeboManager.jar $HOME

WORKDIR $HOME

