FROM gazebo-simulation-manager:latest

WORKDIR $HOME

COPY . $HOME

## chmod a+x for all bash scripts
RUN $INST_SCRIPTS/set_user_permission.sh $HOME $HOME/ws

WORKDIR $HOME/ws/

RUN catkin init --workspace .

RUN chmod +x build.sh

RUN echo "source $HOME/ws/devel/setup.bash" >> ~/.bashrc \
	 && echo "source $HOME/ws/global_variables.env" >> ~/.bashrc

WORKDIR $HOME

RUN mkdir cpswarm

ENV JAVA_HOME /usr/lib/jvm/java-1.8.0-openjdk-amd64/

RUN keytool -noprompt -importcert -trustcacerts \
    -file <JVM-Certifivcation.pem> -alias <xmpp Server Name: pippo.pluto.it> \
    -storepass changeit -keystore -J-Duser.language=en $JAVA_HOME/jre/lib/security/cacerts

ENTRYPOINT ["/home/dockerstartup/vnc_startup.sh"]
CMD ["--wait"]
